#include<iostream.h>
#include<conio.h>
#include<dos.h>
void main()
{
clrscr();
textcolor(12);
cout<<"\n\t\t\t\t    HELP";
cout<<"\n\t\t\t\t-----------" ;
cout<<"\n\nBOOKING:-"<<"\n*******" ;
cout<<"\nTo book a ticket choose 'book a ticket'.Modifying and cancellation is permitted only if the ticket is already booked.";
cout<<"\nEnter the customer and train details to book a ticket.\nOnce the ticket is booked you are given a choice to either display your reservation or to go back.";
cout<<"\nIf not satisfied with the displayed reservation,you may modify or cancel the reservation.";
cout<<"\n\nMODIFY AND CANCELLING \n**********************";
cout<<"\nTo modify or cancel,enter the ID number of the passenger whose reservation you  might want to modify/cancel.\nOnce the record is modified it would be displayed.\nOnce the record is cancelled,you may rebook or exit.";
cout<<"\n\nThe fare details menu option displays the concessions provided on the basis of  age and travel preferences.";
cout<<"\nseat type available:-"  ;
cout<<"1. SL = Sleeper Class  2. 1A = First Class AC  3. 2A = AC 2 Tier 4. 3A = AC 3 Tier  5. CC = AC Chair Car";
cout<<"\n\n\t\t\t\t****THANKYOU FOR CHOOSING TO TRAVEL WITH US****";
getch();
}
