.PHONY: clean All

All:
	@echo "----------Building project:[ initiallyproject - Debug ]----------"
	@cd "initiallyproject" && "$(MAKE)" -f  "initiallyproject.mk"
clean:
	@echo "----------Cleaning project:[ initiallyproject - Debug ]----------"
	@cd "initiallyproject" && "$(MAKE)" -f  "initiallyproject.mk" clean
